export type BibleBook = {
  name: string;
  slug: string;
  chapters: number;
};

export const oldTestamentBooks = [
  { name: "Gênesis", slug: "genesis", chapters: 50 },
  { name: "Êxodo", slug: "exodo", chapters: 40 },
  { name: "Levítico", slug: "levitico", chapters: 27 },
  { name: "Números", slug: "numeros", chapters: 36 },
  { name: "Deuteronômio", slug: "deuteronomio", chapters: 34 },
  { name: "Josué", slug: "josue", chapters: 24 },
  { name: "Juízes", slug: "juizes", chapters: 21 },
  { name: "Rute", slug: "rute", chapters: 4 },
  { name: "1 Samuel", slug: "1-samuel", chapters: 31 },
  { name: "2 Samuel", slug: "2-samuel", chapters: 24 },
  { name: "1 Reis", slug: "1-reis", chapters: 22 },
  { name: "2 Reis", slug: "2-reis", chapters: 25 },
  { name: "1 Crônicas", slug: "1-cronicas", chapters: 29 },
  { name: "2 Crônicas", slug: "2-cronicas", chapters: 36 },
  { name: "Esdras", slug: "esdras", chapters: 10 },
  { name: "Neemias", slug: "neemias", chapters: 13 },
  { name: "Ester", slug: "ester", chapters: 10 },
  { name: "Jó", slug: "jo", chapters: 42 },
  { name: "Salmos", slug: "salmos", chapters: 150 },
  { name: "Provérbios", slug: "proverbios", chapters: 31 },
  { name: "Eclesiastes", slug: "eclesiastes", chapters: 12 },
  { name: "Cânticos", slug: "canticos", chapters: 8 },
  { name: "Isaías", slug: "isaias", chapters: 66 },
  { name: "Jeremias", slug: "jeremias", chapters: 52 },
  { name: "Lamentações", slug: "lamentacoes", chapters: 5 },
  { name: "Ezequiel", slug: "ezequiel", chapters: 48 },
  { name: "Daniel", slug: "daniel", chapters: 12 },
  { name: "Oséias", slug: "oseias", chapters: 14 },
  { name: "Joel", slug: "joel", chapters: 3 },
  { name: "Amós", slug: "amos", chapters: 9 },
  { name: "Obadias", slug: "obadias", chapters: 1 },
  { name: "Jonas", slug: "jonas", chapters: 4 },
  { name: "Miqueias", slug: "miqueias", chapters: 7 },
  { name: "Naum", slug: "naum", chapters: 3 },
  { name: "Habacuque", slug: "habacuque", chapters: 3 },
  { name: "Sofonias", slug: "sofonias", chapters: 3 },
  { name: "Ageu", slug: "ageu", chapters: 2 },
  { name: "Zacarias", slug: "zacarias", chapters: 14 },
  { name: "Malaquias", slug: "malaquias", chapters: 4 },
] as const satisfies readonly BibleBook[];

export const newTestamentBooks = [
  { name: "Mateus", slug: "mateus", chapters: 28 },
  { name: "Marcos", slug: "marcos", chapters: 16 },
  { name: "Lucas", slug: "lucas", chapters: 24 },
  { name: "João", slug: "joao", chapters: 21 },
  { name: "Atos", slug: "atos", chapters: 28 },
  { name: "Romanos", slug: "romanos", chapters: 16 },
  { name: "1 Coríntios", slug: "1-corintios", chapters: 16 },
  { name: "2 Coríntios", slug: "2-corintios", chapters: 13 },
  { name: "Gálatas", slug: "galatas", chapters: 6 },
  { name: "Efésios", slug: "efesios", chapters: 6 },
  { name: "Filipenses", slug: "filipenses", chapters: 4 },
  { name: "Colossenses", slug: "colossenses", chapters: 4 },
  { name: "1 Tessalonicenses", slug: "1-tessalonicenses", chapters: 5 },
  { name: "2 Tessalonicenses", slug: "2-tessalonicenses", chapters: 3 },
  { name: "1 Timóteo", slug: "1-timoteo", chapters: 6 },
  { name: "2 Timóteo", slug: "2-timoteo", chapters: 4 },
  { name: "Tito", slug: "tito", chapters: 3 },
  { name: "Filemom", slug: "filemom", chapters: 1 },
  { name: "Hebreus", slug: "hebreus", chapters: 13 },
  { name: "Tiago", slug: "tiago", chapters: 5 },
  { name: "1 Pedro", slug: "1-pedro", chapters: 5 },
  { name: "2 Pedro", slug: "2-pedro", chapters: 3 },
  { name: "1 João", slug: "1-joao", chapters: 5 },
  { name: "2 João", slug: "2-joao", chapters: 1 },
  { name: "3 João", slug: "3-joao", chapters: 1 },
  { name: "Judas", slug: "judas", chapters: 1 },
  { name: "Apocalipse", slug: "apocalipse", chapters: 22 },
] as const satisfies readonly BibleBook[];

export const bibleBooks: readonly BibleBook[] = [
  ...oldTestamentBooks,
  ...newTestamentBooks,
];
