export type DailyVerse = {
  id: string;
  text: string;
  reference: string;
  translation: "NAA";
};

export const dailyVerses = [
  {
    id: "joao-3-16",
    text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo o que nele crê não pereça, mas tenha a vida eterna.",
    reference: "João 3:16",
    translation: "NAA",
  },
  {
    id: "salmos-23-1",
    text: "O Senhor é o meu pastor; nada me faltará.",
    reference: "Salmos 23:1",
    translation: "NAA",
  },
  {
    id: "isaias-41-10",
    text: "Não tema, porque eu estou com você; não fique com medo, porque eu sou o seu Deus. Eu lhe dou forças; sim, eu o ajudo; sim, eu o seguro com a mão direita da minha justiça.",
    reference: "Isaías 41:10",
    translation: "NAA",
  },
  {
    id: "romanos-12-12",
    text: "Alegrem-se na esperança, sejam pacientes na tribulação e perseverem na oração.",
    reference: "Romanos 12:12",
    translation: "NAA",
  },
  {
    id: "1-corintios-13-13",
    text: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior deles é o amor.",
    reference: "1 Coríntios 13:13",
    translation: "NAA",
  },
  {
    id: "filipenses-4-6",
    text: "Não fiquem preocupados com coisa alguma, mas, em tudo, sejam conhecidos diante de Deus os pedidos de vocês, pela oração e pela súplica, com ações de graças.",
    reference: "Filipenses 4:6",
    translation: "NAA",
  },
  {
    id: "romanos-15-13",
    text: "E o Deus da esperança encha vocês de toda alegria e paz na fé que vocês têm, para que sejam ricos de esperança no poder do Espírito Santo.",
    reference: "Romanos 15:13",
    translation: "NAA",
  },
  {
    id: "salmos-119-105",
    text: "Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.",
    reference: "Salmos 119:105",
    translation: "NAA",
  },
  {
    id: "proverbios-3-5",
    text: "Confie no Senhor de todo o seu coração e não se apoie no seu próprio entendimento.",
    reference: "Provérbios 3:5",
    translation: "NAA",
  },
  {
    id: "mateus-11-28",
    text: "Venham a mim todos vocês que estão cansados e sobrecarregados, e eu os aliviarei.",
    reference: "Mateus 11:28",
    translation: "NAA",
  },
  {
    id: "filipenses-4-13",
    text: "Tudo posso naquele que me fortalece.",
    reference: "Filipenses 4:13",
    translation: "NAA",
  },
  {
    id: "salmos-46-1",
    text: "Deus é o nosso refúgio e a nossa força, socorro que não falta em tempos de aflição.",
    reference: "Salmos 46:1",
    translation: "NAA",
  },
  {
    id: "salmos-37-5",
    text: "Entregue o seu caminho ao Senhor, confie nele, e o mais ele fará.",
    reference: "Salmos 37:5",
    translation: "NAA",
  },
  {
    id: "1-pedro-5-7",
    text: "Lancem sobre ele todas as suas ansiedades, porque ele cuida de vocês.",
    reference: "1 Pedro 5:7",
    translation: "NAA",
  },
  {
    id: "hebreus-13-8",
    text: "Jesus Cristo é o mesmo ontem, hoje e para sempre.",
    reference: "Hebreus 13:8",
    translation: "NAA",
  },
  {
    id: "joao-14-6",
    text: "Eu sou o caminho, a verdade e a vida; ninguém vem ao Pai senão por mim.",
    reference: "João 14:6",
    translation: "NAA",
  },
  {
    id: "2-corintios-5-17",
    text: "E, assim, se alguém está em Cristo, é nova criatura; as coisas antigas já passaram; eis que se fizeram novas.",
    reference: "2 Coríntios 5:17",
    translation: "NAA",
  },
  {
    id: "gálatas-5-22",
    text: "Mas o fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidão e domínio próprio.",
    reference: "Gálatas 5:22-23",
    translation: "NAA",
  },
  {
    id: "mateus-6-33",
    text: "Busquem, pois, em primeiro lugar, o Reino de Deus e a sua justiça, e todas estas coisas lhes serão acrescentadas.",
    reference: "Mateus 6:33",
    translation: "NAA",
  },
  {
    id: "romanos-8-28",
    text: "Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.",
    reference: "Romanos 8:28",
    translation: "NAA",
  },
  {
    id: "josue-1-9",
    text: "Seja forte e corajoso! Não tenha medo, nem fique assustado, porque o Senhor, seu Deus, estará com você por onde quer que você andar.",
    reference: "Josué 1:9",
    translation: "NAA",
  },
  {
    id: "salmos-34-8",
    text: "Provem e vejam que o Senhor é bom; bem-aventurado é quem nele se refugia.",
    reference: "Salmos 34:8",
    translation: "NAA",
  },
  {
    id: "salmos-51-10",
    text: "Cria em mim, ó Deus, um coração puro e renova dentro de mim um espírito inabalável.",
    reference: "Salmos 51:10",
    translation: "NAA",
  },
  {
    id: "salmos-56-3",
    text: "Quando eu ficar com medo, hei de confiar em ti.",
    reference: "Salmos 56:3",
    translation: "NAA",
  },
  {
    id: "salmos-118-24",
    text: "Este é o dia que o Senhor fez; exultemos e alegremo-nos nele.",
    reference: "Salmos 118:24",
    translation: "NAA",
  },
  {
    id: "salmos-121-1-2",
    text: "Elevo os meus olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor, que fez o céu e a terra.",
    reference: "Salmos 121:1-2",
    translation: "NAA",
  },
  {
    id: "salmos-147-3",
    text: "Sara os de coração quebrantado e trata das feridas deles.",
    reference: "Salmos 147:3",
    translation: "NAA",
  },
  {
    id: "proverbios-4-23",
    text: "De tudo o que se deve guardar, guarde bem o seu coração, porque dele procedem as fontes da vida.",
    reference: "Provérbios 4:23",
    translation: "NAA",
  },
  {
    id: "proverbios-16-3",
    text: "Confie ao Senhor as suas obras, e os seus desígnios serão estabelecidos.",
    reference: "Provérbios 16:3",
    translation: "NAA",
  },
  {
    id: "proverbios-17-17",
    text: "O amigo ama em todo tempo, e na angústia nasce o irmão.",
    reference: "Provérbios 17:17",
    translation: "NAA",
  },
  {
    id: "eclesiastes-3-1",
    text: "Tudo tem o seu tempo determinado, e há tempo para todo propósito debaixo do céu.",
    reference: "Eclesiastes 3:1",
    translation: "NAA",
  },
  {
    id: "isaias-40-31",
    text: "Mas os que esperam no Senhor renovam as suas forças, sobem com asas como águias, correm e não se cansam, caminham e não se fatigam.",
    reference: "Isaías 40:31",
    translation: "NAA",
  },
  {
    id: "isaias-43-2",
    text: "Quando você passar pelas águas, eu estarei com você; quando passar pelos rios, eles não o submergirão; quando passar pelo fogo, você não se queimará; as chamas não o atingirão.",
    reference: "Isaías 43:2",
    translation: "NAA",
  },
  {
    id: "jeremias-29-11",
    text: "Eu é que sei que pensamentos tenho a respeito de vocês, diz o Senhor. São pensamentos de paz e não de mal, para dar-lhes um futuro e uma esperança.",
    reference: "Jeremias 29:11",
    translation: "NAA",
  },
  {
    id: "lamentacoes-3-22-23",
    text: "As misericórdias do Senhor são a causa de não sermos consumidos, porque as suas misericórdias não têm fim; renovam-se cada manhã. Grande é a tua fidelidade.",
    reference: "Lamentações 3:22-23",
    translation: "NAA",
  },
  {
    id: "mateus-5-14",
    text: "Vocês são a luz do mundo. Não se pode esconder uma cidade situada no alto de um monte.",
    reference: "Mateus 5:14",
    translation: "NAA",
  },
  {
    id: "mateus-7-7",
    text: "Peçam e lhes será dado; busquem e acharão; batam, e a porta será aberta para vocês.",
    reference: "Mateus 7:7",
    translation: "NAA",
  },
  {
    id: "mateus-19-26",
    text: "Jesus, olhando para eles, disse: — Para os seres humanos isto é impossível, mas para Deus tudo é possível.",
    reference: "Mateus 19:26",
    translation: "NAA",
  },
  {
    id: "marcos-9-23",
    text: "Ao que Jesus respondeu: — ‘Se o senhor pode’? Tudo é possível ao que crê.",
    reference: "Marcos 9:23",
    translation: "NAA",
  },
  {
    id: "lucas-1-37",
    text: "Porque para Deus não há nada impossível.",
    reference: "Lucas 1:37",
    translation: "NAA",
  },
  {
    id: "joao-8-12",
    text: "De novo, Jesus lhes falou, dizendo: — Eu sou a luz do mundo. Quem me segue não andará nas trevas; pelo contrário, terá a luz da vida.",
    reference: "João 8:12",
    translation: "NAA",
  },
  {
    id: "joao-16-33",
    text: "Estas coisas eu disse para que vocês tenham paz em mim. No mundo, vocês passam por aflições; mas tenham coragem: eu venci o mundo.",
    reference: "João 16:33",
    translation: "NAA",
  },
  {
    id: "romanos-8-31",
    text: "Que diremos, então, à vista destas coisas? Se Deus é por nós, quem será contra nós?",
    reference: "Romanos 8:31",
    translation: "NAA",
  },
  {
    id: "romanos-10-17",
    text: "E, assim, a fé vem pelo ouvir, e o ouvir, pela palavra de Cristo.",
    reference: "Romanos 10:17",
    translation: "NAA",
  },
  {
    id: "1-corintios-10-31",
    text: "Portanto, se vocês comem, ou bebem ou fazem qualquer outra coisa, façam tudo para a glória de Deus.",
    reference: "1 Coríntios 10:31",
    translation: "NAA",
  },
  {
    id: "2-corintios-12-9",
    text: "Então ele me disse: — A minha graça é o que basta para você, porque o poder se aperfeiçoa na fraqueza.",
    reference: "2 Coríntios 12:9",
    translation: "NAA",
  },
  {
    id: "galatas-6-9",
    text: "E não nos cansemos de fazer o bem, porque no tempo certo faremos a colheita, se não desanimarmos.",
    reference: "Gálatas 6:9",
    translation: "NAA",
  },
  {
    id: "efesios-4-32",
    text: "Pelo contrário, sejam bondosos e compassivos uns para com os outros, perdoando uns aos outros, como também Deus, em Cristo, perdoou vocês.",
    reference: "Efésios 4:32",
    translation: "NAA",
  },
  {
    id: "filipenses-4-4",
    text: "Alegrem-se sempre no Senhor; outra vez digo: alegrem-se!",
    reference: "Filipenses 4:4",
    translation: "NAA",
  },
  {
    id: "colossenses-3-23",
    text: "Tudo o que fizerem, façam de todo o coração, como para o Senhor e não para as pessoas.",
    reference: "Colossenses 3:23",
    translation: "NAA",
  },
  {
    id: "1-tessalonicenses-5-16-18",
    text: "Estejam sempre alegres. Orem sem cessar. Em tudo, deem graças, porque esta é a vontade de Deus para vocês em Cristo Jesus.",
    reference: "1 Tessalonicenses 5:16-18",
    translation: "NAA",
  },
] as const satisfies readonly DailyVerse[];
